

import { Geist, Geist_Mono } from "next/font/google";
import TopLoader from "@/components/TopLoader";
import Scripts from "@/components/Scripts";

import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import LayoutWrapper from "@/components/LayoutWrapper";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body>
        <Scripts />
        
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-KH8ZPGBR"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>
      
        <TopLoader />

        <LayoutWrapper>
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
